### ISSUE TITLE
Todo xDemic Architecture

### ISSUE THREAD

**Issue by rizwanzaheer** [hoola-inc/xdemic#13]
- [ ] xDemic Architecture todo ( https://github.com/hoola-inc/xDemic-Specs/blob/master/Architecture.md )
- [ ] Identity Hub Reference Implementation ( https://github.com/hoola-inc/hub-reference )
- [ ] Microsoft example ( https://beta.discover.did.microsoft.com/ )
- [ ] uni-resolver-driver-did-uport docker image ( https://hub.docker.com/r/uport/uni-resolver-driver-did-uport/ )
